from pathlib import Path
from typing import Any, Union

__version__: str

InputType = Union[str, Path, bytes, bytearray]

def inspect_file(target: InputType, *, include_source: bool = True) -> dict[str, Any]: ...
def inspect_file_json(target: InputType, *, include_source: bool = True) -> str: ...
def inspect_file_markdown(target: InputType) -> str: ...
def inspect_file_sarif(target: InputType, *, file_uri: str | None = None) -> str: ...
def analyze_sources(sources: list[tuple[str, str]], *, include_source: bool = True) -> dict[str, Any]: ...
def analyze_sources_json(sources: list[tuple[str, str]], *, include_source: bool = True) -> str: ...
